import {
  Action,
  AnyAction,
  createAsyncThunk,
  createSlice,
} from "@reduxjs/toolkit";
import axios from "axios";
import { toast } from "react-toastify";
import type { RootState } from "../../store";

// here we are typing the types for the state
export type MainState = {
  monthlyReport: any;
  monthlyArrival: any;
  monthlyPeakTime: any;
  pending: boolean;
  error: boolean;
  message: any;
};

const initialState: MainState = {
  monthlyReport: {},
  monthlyArrival: {},
  monthlyPeakTime: {},
  pending: false,
  error: false,
  message: "",
};

interface HeadersConfiguration {
  params?: any;
  headers: {
    "Content-Type"?: string;
    Accept?: string;
    Authorization?: string;
  };
}

interface RfidData {
  id?: any;
  data?: any;
  token?: any;
  isSuccess: () => void;
}

interface DefaultGetData {
  id?: any;
  token?: any;
  params?: any;
}

// rejection
interface RejectedAction extends Action {
  error: Error;
}

function isRejectedAction(action: AnyAction): action is RejectedAction {
  return action.type.endsWith("rejected");
}

// get all report
export const getMonthlyReport = createAsyncThunk<
  any,
  DefaultGetData,
  { state: RootState }
>("dashboard/monthly/report", async (params, { getState }) => {
  let config: HeadersConfiguration = {
    params: params.params,
    headers: {
      "Content-Type": "application/json",
      Accept: "application/json",
      Authorization: `Bearer ${params.token}`,
    },
  };
  try {
    const response = await axios.get("dashboard/monthly/report", config);
    const { data, status } = response;
    if (status == 200) {
      return data;
    } else {
      throw response;
    }
  } catch (error: any) {
    const { data, status } = error.response;
    let newError: any = { message: data.message[0] };
    toast.dark(newError.message);
    if (error.response && error.response.status === 404) {
      throw new Error("rfid not found");
    } else {
      throw new Error(newError.message);
    }
  }
});

export const getMonthlyArrival = createAsyncThunk<
  any,
  DefaultGetData,
  { state: RootState }
>("dashboard/monthly/arrival", async (params, { getState }) => {
  let config: HeadersConfiguration = {
    params: params.params,
    headers: {
      "Content-Type": "application/json",
      Accept: "application/json",
      Authorization: `Bearer ${params.token}`,
    },
  };
  try {
    const response = await axios.get("dashboard/monthly/arrival", config);
    const { data, status } = response;
    if (status == 200) {
      return data;
    } else {
      throw response;
    }
  } catch (error: any) {
    const { data, status } = error.response;
    let newError: any = { message: data.message[0] };
    toast.dark(newError.message);
    if (error.response && error.response.status === 404) {
      throw new Error("rfid not found");
    } else {
      throw new Error(newError.message);
    }
  }
});

export const getMonthlyPeekTime = createAsyncThunk<
  any,
  DefaultGetData,
  { state: RootState }
>("dashboard/monthly/peekTime", async (params, { getState }) => {
  let config: HeadersConfiguration = {
    params: params.params,
    headers: {
      "Content-Type": "application/json",
      Accept: "application/json",
      Authorization: `Bearer ${params.token}`,
    },
  };
  try {
    const response = await axios.get("dashboard/monthly/peekTime", config);
    const { data, status } = response;
    if (status == 200) {
      return data;
    } else {
      throw response;
    }
  } catch (error: any) {
    const { data, status } = error.response;
    let newError: any = { message: data.message[0] };
    toast.dark(newError.message);
    if (error.response && error.response.status === 404) {
      throw new Error("rfid not found");
    } else {
      throw new Error(newError.message);
    }
  }
});

// SLICER
export const monthlySlice = createSlice({
  name: "monthly",
  initialState,
  reducers: {
    // leave this empty here
    resetMonthlyReport(state) {
      state.monthlyReport = {};
      state.pending = false;
      state.error = false;
      state.message = "";
    },

    resetMonthlyArrival(state) {
      state.monthlyArrival = {};
      state.pending = false;
      state.error = false;
      state.message = "";
    },

    resetMonthlyPeekTime(state) {
      state.monthlyPeakTime = {};
      state.pending = false;
      state.error = false;
      state.message = "";
    },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere, including actions generated by createAsyncThunk or in other slices.
  // Since this is an API call we have 3 possible outcomes: pending, fulfilled and rejected. We have made allocations for all 3 outcomes.
  // Doing this is good practice as we can tap into the status of the API call and give our rfids an idea of what's happening in the background.
  extraReducers: (builder) => {
    builder
      // get-report
      .addCase(getMonthlyReport.pending, (state) => {
        return {
          ...state,
          pending: true,
        };
      })
      .addCase(getMonthlyReport.fulfilled, (state, { payload }) => {
        return {
          ...state,
          pending: false,
          error: false,
          monthlyReport: payload,
        };
      })
      .addCase(getMonthlyReport.rejected, (state, { error }) => {
        state.pending = false;
        state.error = true;
        state.message = error.message;
      })

      // get-arrival
      .addCase(getMonthlyArrival.pending, (state) => {
        return {
          ...state,
          pending: true,
        };
      })
      .addCase(getMonthlyArrival.fulfilled, (state, { payload }) => {
        return {
          ...state,
          pending: false,
          error: false,
          monthlyArrival: payload,
        };
      })
      .addCase(getMonthlyArrival.rejected, (state, { error }) => {
        state.pending = false;
        state.error = true;
        state.message = error.message;
      })

      // get-report
      .addCase(getMonthlyPeekTime.pending, (state) => {
        return {
          ...state,
          pending: true,
        };
      })
      .addCase(getMonthlyPeekTime.fulfilled, (state, { payload }) => {
        return {
          ...state,
          pending: false,
          error: false,
          monthlyPeakTime: payload,
        };
      })
      .addCase(getMonthlyPeekTime.rejected, (state, { error }) => {
        state.pending = false;
        state.error = true;
        state.message = error.message;
      })

      .addMatcher(isRejectedAction, (state, action) => {})
      .addDefaultCase((state, action) => {
        let base = {
          ...state,
          ...action.state,
        };
        return base;
      });
  },
});
// SLICER

const monthlyReducers = monthlySlice.reducer;

export const { resetMonthlyReport, resetMonthlyArrival, resetMonthlyPeekTime } =
  monthlySlice.actions;
export const selectMonthlyManagement = (state: RootState) =>
  state.monthlyManagement;

export default monthlyReducers;
